config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {registrations: "users/registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show] do
      
  end
  
  resources :memos do
    resources :todos do
        member do
          get "sort"
        end
    end
  end
  
  resources :tweets do
      collection do
        get 'search'
        get 'favorite'
      end
      
    resources :likes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  get "users/:id" => "users#show"
  
  root to: "home#index"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
  # image の追加
      mount_uploader :image, ImageUploader
  # liked_usersによって投稿が誰にいいねされているのかを簡単に取得できる
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  # 上記と同様
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  # コメント機能追加
  has_many :comments, dependent: :destroy
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :authenticate_user!, only: [:show, :create, :favorite]
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :login_check, only: [:new, :edit, :update, :destroy, :favorite]
  before_action :set_q, only: [:index, :search]

  # GET /tweets
  def index
    @tweets = Tweet.order("id DESC")
    @tweet = Tweet.new
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.includes(:user).find(params[:id])
    @like = Like.new
    @favorite = Favorite.new
    @comments = @tweet.comments
    @comment = current_user.comments.new

  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  def create
    @tweet = current_user.tweets.build(tweet_params)
    if @tweet.save
      redirect_to tweets_path

    else
      render :new
    end
  end

  # PATCH/PUT /tweets/1
  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet.destroy
    redirect_to tweets_url, notice: '投稿が削除されました'
  end

  def search
    @results = @q.result
  end

  def favorite
    @favorite = current_user.favorited_tweets
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def login_check
      unless user_signed_in?
        flash[:alert] = "ログインしてください"
        redirect_to root_path
      end
    end
    
    def set_tweet
      @tweet = current_user.tweets.find_by(id: params[:id])
    end
    # ransackメソッド検索するメソッド
    def set_q
      @q = Tweet.ransack(params[:q])
    end

    # Only allow a trusted parameter "white list" through.
    def tweet_params
      params.require(:tweet).permit(:content, :user_id, :image)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> このツイートの保存を禁止しました</h2>
      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%# 画像アップロード %>
  <div class="field form-group">
    <%= form.label "#", class: "text-light" %>
    <%= form.file_field :image %>
  </div>
<%# 投稿内容 %>
  <div class="field form-group">
    <h6><%= form.label "投稿内容", class: "text-success" %></h6>
        <%= form.text_field :content, id: :tweet_content, class:"form-control" %>
  </div>

  <div class="text-left">
    <%= form.submit "投 稿", class: "btn btn-outline-success" %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="card mb-3">
    <div class="card-body">
        <p class="card-text"><a href="/users/<%= tweet.user.id %>"><%= tweet.user.user_name %></p>
        <p class="card-text"><a href="/tweets/<%= tweet.id %>"><%= tweet.content %></p>
            <%# 編集、削除ボタンの制御 %>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <% if user_signed_in? && tweet.user == current_user %>
            <div class="text-right" class="text-top">
                <%= link_to '編集', edit_tweet_path(tweet), class: "btn btn-outline-primary" %>
                <%= link_to '削除', tweet, method: :delete, class: "btn btn-outline-warning" %>
            </div>
            <% end %>
        </div>
            <% if tweet.image? %>
                <%= image_tag tweet.image.url, :size =>'420x500' %>
            <% end %>

            <% if user_signed_in? %>
                    <div class="btn-group text-left" role="group">
                <%# いいね機能ボタン %>
                        <% if current_user.already_liked?(tweet) %>
                        <div class="btn btn-outline-success">
                            <%= link_to 'いいね解除', tweet_like_path(id: tweet.id, tweet_id: tweet.id), method: :delete %>
                            <%= tweet.likes.count %>
                        </div>
                        <% else %>
                        <div class="btn btn-outline-success">
                            <%= link_to 'いいね', tweet_likes_path(id: tweet.id, tweet_id: tweet.id), method: :post %>
                            <%= tweet.likes.count %>
                        </div>
                        <% end %>
                <%# お気に入り機能ボタン %>
                        <% if current_user.already_favorited?(tweet) %>
                        <div class="btn btn-outline-success">
                            <%= link_to 'お気に入り解除', tweet_favorite_path(id: tweet.id, tweet_id: tweet.id), method: :delete %>
                            <%= tweet.favorites.count %>   
                        </div>            
                        <% else %>
                        <div class="btn btn-outline-success">
                            <%= link_to 'お気に入り', tweet_favorites_path(id: tweet.id, tweet_id: tweet.id), method: :post %>
                            <%= tweet.favorites.count %>
                        </div>
                        <% end %>
                        </div>
                    <% end %>
            <%# Jqueryの動きを出すためのコード3種 %>
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></scri
    </div>
</div>

app/views/tweets/edit.html.erb
<div class="card m-5 h-75 border-success">
<div class="card-header title-1 border-success">投稿編集</div>
    <div class="card-body p-4">
        <%= render 'form', tweet: @tweet %>
        <%= link_to '戻る', tweets_path, class: "btn btn-outline-success" %>
    </div>
</div>

app/views/tweets/favorite.html.erb
<div class="card mb-3">
        <div class="card-body">
            <div class="field">
                <h6>いいねしている投稿</h6>
                <% @favorite.each do |tweet| %>
                    <%= tweet.content %>
                    <%= tweet.user.user_name %>
                <% end %>
            </div>
        </div>
        </div>

app/views/tweets/index.html.erb
<div class="d-flex ml-4">
  <div class="title-1 mb-2 ml-5 pl-5 mr-5 pr-5">投稿一覧</div>
    <div class="pt-2 pl-5 ml-5">
      <%# 検索機能追加 %>
      <%= search_form_for @q, url: search_tweets_path do |f| %>
          <%= f.label :content_cont, "投稿", class: "text-success pr-2" %>
          <%= f.search_field :content_cont, class: "btn btn-light btn-sm border-success" %>
          <%= f.submit "検索", class: "btn btn-light btn-md text-success" %>
      <% end %>
    </div>
</div>
<%# 画面スクロール 修正できたためコメントアウト %>
<%# <div class="scroll"> %>
    <div class="row">
      <% @tweets.each do |tweet| %>
        <div class="col-4 pr-1 pl-1 pb-2">
          <div class="card border-success" style="height: 25em">
              <div class="card-header bg-success px-2 py-1 text-right">
                <div class="d-flex">
                  <%# ユーザー画像 %>
                  <div class="image">
                    <% if tweet.user.image? %>
                        <%= image_tag tweet.user.image.url, class: "rounded-circle", :size =>'70x65' %>
                    <% else %>
                        <%= image_tag 'default_profile_user_icon.png', class: "rounded-circle bg-light", :size =>'70x65' %>
                    <% end %>
                  </div>
                  <%# ユーザーネーム 投稿してる他のユーザー詳細にアクセスできる %>
                  <div class="pl-2 pt-3 text-left"><%= link_to tweet.user.user_name, user_path(tweet.user) , class: "card-title h5 pt-3 text-left text-light font-weight-bold" %></div>
                  <%# dropdowe-menuがリンクに飛ばされた後、何らかの原因で使用できないので 代換えしている %>
                  <div class="Po">
                    <details>
                      <summary  class='fas fa-ellipsis-v h4 pt-1 pr-0 text-white d-block'></summary>
                      <ul class="mt-2 pt-3 p-0 text-center">
                            <li class="h5 py-1 my-0"><%= link_to '詳細', tweet_path(tweet), class: "text-success" %></li>
                          <%# 編集、削除ボタンの制御 %>
                          <% if user_signed_in? && tweet.user == current_user %>
                            <li class="h5 py-1 my-0"><%= link_to '編集', edit_tweet_path(tweet), class: "text-success" %></li>
                            <li class="h5 py-1 my-0"><%= link_to '削除', tweet, method: :delete, class: "text-danger", remote: true, data: { confirm: '削除しますか？' } %></li>
                          <% end %>
                      </ul>
                    </details>
                  </div>
                </div>
              </div>
              <%# Body %>
              <div class="card-body p-3 overflow-auto">
                <%# 画像 %>
                <% if tweet.image? %>
                    <%= image_tag tweet.image.url, class: "card-img-top mb-3", style: "height:14em" %>
                <% end %>
                <%# 投稿内容 %>
                <p class="card-text"><%= tweet.content %></p>
              </div>
              <%# Fooyer %>
              <div class="card-footer bg-light border-light pb-0 pt-0 pl-3 pr-0">
                <% if user_signed_in? %>
                  <div class="btn-group text-left pb-2" role="group">
                    <%# いいね機能ボタン %>
                    <% if current_user.already_liked?(tweet) %>
                      <div class="btn btn-success border-light">
                        <%= link_to '#', tweet_like_path(id: tweet.id, tweet_id: tweet.id), method: :delete, class: "position" %>
                            <span class='fas fa-heart fa-lg' style='color:#ff00ae'></span>
                        <%= tweet.likes.count %>
                      </div>
                    <% else %>
                      <div class="btn btn-success border-light">
                        <%= link_to "#", tweet_likes_path(id: tweet.id, tweet_id: tweet.id), method: :post, class: "position" %>
                            <span class='fas fa-heart fa-lg' style='color:#ff00ae'></span>
                        <%= tweet.likes.count %>
                      </div>
                    <% end %>
                    <%# お気に入り機能ボタン %>
                    <% if current_user.already_favorited?(tweet) %>
                      <div class="btn btn-success border-light">
                        <%= link_to '#', tweet_favorite_path(id: tweet.id, tweet_id: tweet.id), method: :delete, class: "screen" %>
                          <span class='fas fa-star fa-lg' style='color:#f0ff24'></span>
                        <%= tweet.favorites.count %>   
                      </div>            
                    <% else %>
                      <div class="btn btn-success border-light">
                        <%= link_to '#', tweet_favorites_path(id: tweet.id, tweet_id: tweet.id), method: :post, class: "screen" %>
                          <span class='fas fa-star fa-lg' style='color:#f0ff24'></span>
                        <%= tweet.favorites.count %>
                      </div>
                    <% end %>
                  </div>
                <% end %>
              </div>
          </div>
        </div>
      <% end %>
    </div>
    <button class="btn btn-outline-success mt-3">
      <a href="#" id="page-top" class="text-success font-weight-bold">TOP→</a>
    </button>
<%# </div>  %>

app/views/tweets/new.html.erb
<div class="card m-5 h-75 border-success">
  <div class="card-header title-1 border-success">新規投稿</div>
  <div class="card-body p-4">
    <%= render 'form', tweet: @tweet %>
    <%= link_to '戻る', tweets_path, class: "btn btn-outline-success" %>
  </div>
</div>

app/views/tweets/search.html.erb
<div class="d-flex ml-4">
    <div class="title-1 mb-2 ml-5 pl-5 mr-5 pr-5">投稿一覧</div>
        <div class="pt-2 pl-5 ml-5">
            <%# 検索機能追加 %>
            <%= search_form_for @q, url: search_tweets_path do |f| %>
                <%= f.label :content_cont, "投稿", class: "text-success pr-2" %>
                <%= f.search_field :content_cont, class: "btn btn-light btn-sm border-success" %>
                <%= f.submit "検索", class: "btn btn-light btn-md text-success" %>
            <% end %>
        </div>
</div>
<%# 画面スクロール 修正できたためコメントアウト %>
<%# <div class="scroll"> %>
<div class="row pl-2 pr-2">
    <% @results.each do |tweet| %>
        <div class="col-4 pr-1 pl-1 pb-2">
        <div class="card border-success" style="height: 25em">
            <div class="card-header bg-success px-2 py-1 text-right">
                <div class="d-flex">
                <%# ユーザー画像 %>
                <div class="image">
                    <% if tweet.user.image? %>
                        <%= image_tag tweet.user.image.url, class: "rounded-circle", :size =>'70x65' %>
                    <% else %>
                        <%= image_tag 'default_profile_user_icon.png', class: "rounded-circle bg-light", :size =>'70x65' %>
                    <% end %>
                </div>
                <%# ユーザーネーム 投稿してる他のユーザー詳細にアクセスできる %>
                <div class="pl-2 pt-3 text-left"><%= link_to tweet.user.user_name, user_path(tweet.user) , class: "card-title h5 pt-3 text-left text-light font-weight-bold" %></div>
                <%# dropdowe-menuがリンクに飛ばされた後、何らかの原因で使用できないので 代換えしている %>
                <div class="Po">
                    <details>
                    <summary  class='fas fa-ellipsis-v h4 pt-1 pr-0 text-white d-block'></summary>
                    <ul class="mt-2 pt-3 p-0 text-center">
                            <li class="h5 py-1 my-0"><%= link_to '詳細', tweet_path(tweet), class: "text-success" %></li>
                        <%# 編集、削除ボタンの制御 %>
                        <% if user_signed_in? && tweet.user == current_user %>
                            <li class="h5 py-1 my-0"><%= link_to '編集', edit_tweet_path(tweet), class: "text-success" %></li>
                            <li class="h5 py-1 my-0"><%= link_to '削除', tweet, method: :delete, class: "text-danger", remote: true, data: { confirm: '削除しますか？' } %></li>
                        <% end %>
                    </ul>
                    </details>
                </div>
                </div>
            </div>
            <%# Body %>
            <div class="card-body p-3 overflow-auto">
                <%# 画像 %>
                <% if tweet.image? %>
                    <%= image_tag tweet.image.url, class: "card-img-top mb-3", style: "height:14em" %>
                <% end %>
                <%# 投稿内容 %>
                <p class="card-text"><%= tweet.content %></p>
            </div>
            <%# Fooyer %>
            <div class="card-footer bg-light border-light pb-0 pt-0 pl-3 pr-0">
                <% if user_signed_in? %>
                <div class="btn-group text-left pb-2" role="group">
                    <%# いいね機能ボタン %>
                    <% if current_user.already_liked?(tweet) %>
                    <div class="btn btn-success border-light">
                        <%= link_to '#', tweet_like_path(id: tweet.id, tweet_id: tweet.id), method: :delete, class: "position" %>
                            <span class='fas fa-heart fa-lg' style='color:#ff00ae'></span>
                        <%= tweet.likes.count %>
                    </div>
                    <% else %>
                    <div class="btn btn-success border-light">
                        <%= link_to "#", tweet_likes_path(id: tweet.id, tweet_id: tweet.id), method: :post, class: "position" %>
                            <span class='fas fa-heart fa-lg' style='color:#ff00ae'></span>
                        <%= tweet.likes.count %>
                    </div>
                    <% end %>
                    <%# お気に入り機能ボタン %>
                    <% if current_user.already_favorited?(tweet) %>
                    <div class="btn btn-success border-light">
                        <%= link_to '#', tweet_favorite_path(id: tweet.id, tweet_id: tweet.id), method: :delete, class: "screen" %>
                        <span class='fas fa-star fa-lg' style='color:#f0ff24'></span>
                        <%= tweet.favorites.count %>   
                    </div>            
                    <% else %>
                    <div class="btn btn-success border-light">
                        <%= link_to '#', tweet_favorites_path(id: tweet.id, tweet_id: tweet.id), method: :post, class: "screen" %>
                        <span class='fas fa-star fa-lg' style='color:#f0ff24'></span>
                        <%= tweet.favorites.count %>
                    </div>
                    <% end %>
                </div>
                <% end %>
            </div>
        </div>
        </div>
    <% end %>
</div>
<button class="btn btn-outline-success mt-3">
    <a href="#" id="page-top" class="text-success font-weight-bold">TOP→</a>
</button>
<%# </div>  %>

app/views/tweets/show.html.erb
<div class="card mb-3 border-success">
<div class="card-header bg-success text-light d-flex">
    <%# ユーザーネーム %>
    <div class="w-100"><h3 class="card-title pt-0 text-center text-light font-weight-bold"><%= @tweet.user.user_name %></h3></div>
    <%# dropdowe-menuがリンクに飛ばされた後、何らかの原因で使用できないので 代換えしている %>
    <div class="w-0">
        <details>
            <summary  class='fas fa-ellipsis-v h4 pt-1 pr-0 text-white d-block'></summary>
            <ul class="mt-2 pt-3 p-0 text-center">
                <%# 編集、削除ボタンの制御 %>
                <% if user_signed_in? && @tweet.user == current_user %>
                    <li class="h4 py-1 my-0"><%= link_to '編集', edit_tweet_path(@tweet), class: "text-success" %></li>
                    <li class="h4 py-1 my-0"><%= link_to '削除', @tweet, method: :delete, class: "text-danger", remote: true, data: { confirm: '削除しますか？' } %></li>
                <% end %>
            </ul>
        </details>
    </div>
</div>
    <% if @tweet.image? %>
        <%= image_tag @tweet.image.url,  class: "card-img-top", size: "400x520" %>
    <% end %>
    <div class="card-body border-success pl-5">
        <p class="card-text font-weight-bold"><%= @tweet.content %></p>
    </div>
    <div class="card-footer bg-success pl-5">
        <h6 class="text-light font-weight-bold"> コメント</h6>
        <div class="d-flex">
            <%= form_with(model:[@tweet, @comment], method: :post) do |f| %>
                <%= f.text_area :comment_content %>
                <%= f.hidden_field :tweet_id, value: @tweet.id %>
                <%= f.submit '送信', class: "bg-light border-light" %>
            <% end %>
            <% if user_signed_in? %>
                <div class="btn-group text-right pt-3" role="group">
                <%# いいね機能ボタン %>
                <% if current_user.already_liked?(@tweet) %>
                    <div class="btn btn-light border-success pt-1 mb-5">
                    <%= link_to '#', tweet_like_path(id: @tweet.id, tweet_id: @tweet.id), method: :delete, class: "position" %>
                        <span class='fas fa-heart fa-lg' style='color:#ff00ae'></span>
                    <%= @tweet.likes.count %>
                    </div>
                <% else %>
                    <div class="btn btn-light border-success pt-1 mb-5">
                    <%= link_to "#", tweet_likes_path(id: @tweet.id, tweet_id: @tweet.id), method: :post, class: "position" %>
                        <span class='fas fa-heart fa-lg' style='color:#ff00ae'></span>
                    <%= @tweet.likes.count %>
                    </div>
                <% end %>
                <%# お気に入り機能ボタン %>
                <% if current_user.already_favorited?(@tweet) %>
                    <div class="btn btn-light border-success pt-1 mb-5">
                    <%= link_to '#', tweet_favorite_path(id: @tweet.id, tweet_id: @tweet.id), method: :delete, class: "screen" %>
                        <span class='fas fa-star fa-lg' style='color:#f0ff24'></span>
                    <%= @tweet.favorites.count %>   
                    </div>            
                <% else %>
                    <div class="btn btn-light border-success pt-1 mb-5">
                    <%= link_to '#', tweet_favorites_path(id: @tweet.id, tweet_id: @tweet.id), method: :post, class: "screen" %>
                        <span class='fas fa-star fa-lg' style='color:#f0ff24'></span>
                    <%= @tweet.favorites.count %>
                    </div>
                <% end %>
                </div>
            <% end %>
        </div>
        <h6 class="text-light font-weight-bold"> コメント一覧</h6>
            <%# コメントの内容が表示される %>
            <% @comments.each do |comment| %>
            <div class="card">
                <div class="pl-3">
                    <%= @current_user.user_name %>
                </div>
                <div class="pl-2">
                    <%= comment.comment_content %>
                </div>
            <% end %>
            </div>
</div>
</div>