config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {registrations: "users/registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show] do
      
  end
  
  resources :memos do
    resources :todos do
        member do
          get "sort"
        end
    end
  end
  
  resources :tweets do
      collection do
        get 'search'
        get 'favorite'
      end
      
    resources :likes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  get "users/:id" => "users#show"
  
  root to: "home#index"
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :memo
  acts_as_list scope: [:memo_id]

  validates :position, numericality: { only_integer: true, allow_nil: true }
  validates :content, presence: true
  validates :done, inclusion: { in: [true, false] }

  after_initialize :set_default, if: :new_record?

  private

  def set_default
    self.done = false if self.done.blank?
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_memo
  before_action :set_todo, only: [:show, :edit, :update, :destroy, :sort]

  # GET /todos/new
  def new
    @todo = @memo.todos.new
  end

  # GET /todos/1/edit
  def edit
  end

  def sort
  end

  # POST /todos
  def create
    @todo = @memo.todos.new(todo_params)

    if @todo.save
      @status = true
    else
      @status = false
    end
  end

  # PATCH/PUT /todos/1
  def update
    if @todo.update(todo_params)
      @status = true
    else
      @status = false
    end
  end

  # DELETE /todos/1
  def destroy
    @todo.destroy
  end

  private
    def set_memo
      @memo = current_user.memos.find_by(id: params[:memo_id])
      redirect_to(memos_url, alert: "ERROR!!") if @memo.blank?
    end

    def set_todo
      @todo = @memo.todos.find_by(id: params[:id])
    end

    def todo_params
      params.require(:todo).permit(:content, :memo_id, :position, :done)
    end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_form.html.erb
<%= form_with(model: todo, url: [memo, todo], remote: true, html: {name: "todoForm", class: "p-2"} ) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>
      <ul>
        <% todo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_area :content, rows: 4 %>
  </div>
  <div class="actions text-right">
    <%= link_to "閉じる", new_memo_todo_path(memo), class: "btn btn-secondary text-light", remote: true %>
    <%= form.submit "作成", class: "btn-success" %>
  </div>
<% end %>

app/views/todos/_modal_form.html.erb
<div class="modal fade" id="memoModal" tabindex="-1" role="dialog" aria-labelledby="memoModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <%= form_with(model: todo, url: [memo, todo], remote: true, class: "") do |form| %>
            <div class="modal-header">
            <h4 class="modal-title text-success" id="memoModal">TODOリスト編集</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
            <% if todo.errors.any? %>
                <div id="error_explanation">
                <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>
                <ul>
                    <% todo.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                </ul>
                </div>
            <% end %>
            <div class="field text-success">
                <%= form.label :content, "内容" %>
                <%= form.text_area :content, rows: 5 %>
            </div>
            </div>
            <div class="modal-footer actions">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
            <%= form.submit "更新" %>
            </div>
        <% end %>
        </div>
    </div>
</div>

app/views/todos/_modal_sort_form.html.erb
<div class="modal fade" id="memoModal" tabindex="-1" role="dialog" aria-labelledby="memoModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <%= form_with(model: todo, url: [memo, todo], remote: true, class: "") do |form| %>
            <div class="modal-header">
            <h4 class="modal-title text-success" id="memoModal">並びかえ</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
            <% if todo.errors.any? %>
                <div id="error_explanation">
                <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>
                <ul>
                    <% todo.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                </ul>
                </div>
            <% end %>
            <div class="card my-2">
                <div class="card-body">
                <div class="card-text">
                    <%= todo.done ? tag.del(){simple_format todo.content} : (simple_format todo.content) %>
                </div>
                <div class="card-text">
                    <small class="text-muted">
                    <%= l(todo.created_at, format: :short) if todo.created_at.present? %>
                    </small>
                </div>
                </div>
            </div>
            <div class="fiel text-success">
                <%= form.label :position, class: "d-none"  %>
                <%= form.select  :position,
                (1..memo.todos.length).map {|i| [i, i] },
                { selected: memo.todos.index(todo) + 1 },
                class: "d-inline w-auto text-success" %>番目に移動
            </div>
            <div class="modal-footer actions">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
                <%= form.submit "更新" %>
            </div>
            </div>
        <% end %>
        </div>
    </div>
</div>

app/views/todos/_todo.html.erb
<div class="card mt-2 todo-card <%=" text-muted bg-light" if todo.done %>"data-model_name="<%= Todo.model_name.singular %>"data-memo_id="<%= todo.memo.id %>"data-id="<%= todo.id %>">
    <div class="card-body pr-1">
        <div class="card-text pr-4">
            <%= todo.done ? tag.del(){simple_format todo.content} : (simple_format todo.content) %>
        </div>
        <div class="btn-group position-absolute" style="top: 10px; right: 4px">
            <button type="button" class="btn text-success" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right text-middle">
                <%= form_with(model: todo, url: [todo.memo, todo], remote: true) do |form| %>
                    <% if todo.done %>
                        <%= form.hidden_field :done, value: false, readonly: true %>
                        <%= form.submit "未完了", class: "dropdown-item text-info" %>
                    <% else %>
                        <%= form.hidden_field :done, value: true, readonly: true %>
                        <%= form.submit "完了！", class: "dropdown-item text-info" %>
                    <% end %>
                <% end %>
                <div class="dropdown-divider"></div>
                <%= link_to "並びかえ", sort_memo_todo_path(todo.memo, todo), class: "dropdown-item text-success", remote: true %>
                <%= link_to "編集", edit_memo_todo_path(todo.memo, todo), class: "dropdown-item text-success", remote: true %>
                <%= link_to "削除", memo_todo_path(todo.memo, todo), method: :delete, class: "dropdown-item text-danger", remote: true, data: { confirm: 'Are you sure?' } %>
            </div>
        </div>
        <div class="card-text">
            <small class="text-muted">
                <%= todo.created_at.strftime('%Y/%m/%d') %>
            </small>
        </div>
    </div>
</div>

app/views/todos/create.js.erb
<%# Rails @status => true formの内容消去、要素の追加 : false モーダルを再度表示 %>
<% if @status %>
<%# formを空にする / formにフォーカスする %>
$('[data-model_name="memo"]').filter('[data-id="<%= @memo.id %>"]').find('form [name="todo[content]"]').val("")
$('[data-model_name="memo"]').filter('[data-id="<%= @memo.id %>"]').find('form [name="todo[content]"]').eq(0).focus();

<%# 順序が入れ替わるため、todosを描画しなおす %>
$('[data-model_name="memo"]').filter('[data-id="<%= @memo.id %>"]').find(".todo-cards").html("<%= j(render partial: 'todos/todo', collection: @memo.todos, as: :todo) %>");

<% else %>
$('[data-model_name="memo"]').filter('[data-id="<%= @memo.id %>"]').find('form [name="todo[content]"]').eq(0).focus();
<% end %>

app/views/todos/destroy.js.erb
<%# 画面の書き換え %>
$('[data-model_name="todo"]').filter('[data-memo_id="<%= @memo.id %>"][data-id="<%= @todo.id %>"]').remove();

app/views/todos/edit.js.erb
<%# モーダル追加 %>
$("#modalArea").html(
    "<%= j(render 'modal_form', todo: @todo, memo: @memo) %>"
);

<%# フォームにフォーカス %>
$("#modalArea").find(".modal").on('shown.bs.modal', () => {
    $("#modalArea").find('form [name="todo[content]"]').eq(0).focus();
})

<%# モーダル表示 %>
$("#modalArea").find(".modal").modal("show");

app/views/todos/new.js.erb
<%# true すでに一度フォームが表示されている場合 : false まだフォームが表示されてない場合 %>
if ($('[data-model_name="memo"]').filter('[data-id="<%= @memo.id %>"]').find('form[name="todoForm"]').length) {
    $('[data-model_name="memo"]').filter('[data-id="<%= @memo.id %>"]').find('form[name="todoForm"]').eq(0).toggle()
    $('[data-model_name="memo"]').filter('[data-id="<%= @memo.id %>"]').find('form [name="todo[content]"]').eq(0).focus();
} else {
    $('[data-model_name="memo"]').filter('[data-id="<%= @memo.id %>"]').find('.memo-header').after("<%= j(render 'form', memo: @memo, todo: @todo) %>")
    $('[data-model_name="memo"]').filter('[data-id="<%= @memo.id %>"]').find('form [name="todo[content]"]').eq(0).focus();
}

app/views/todos/sort.js.erb
<%# 画面の書き換え %>
<%# モーダル追加 %>
$("#modalArea").html(
    "<%= j(render 'modal_sort_form', todo: @todo, memo: @memo) %>"
);
<%# フォームにフォーカス %>
$("#modalArea").find(".modal").on('shown.bs.modal', () => {
    $("#modalArea").find('form [name="todo[content]"]').eq(0).focus();
})

<%# モーダル表示 %>
$("#modalArea").find(".modal").modal("show");

app/views/todos/update.js.erb
<%# モーダルを閉じる処理 %>
$("#memoModal").modal("hide");
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();

<%# Rails @status => true 画面の書き換え : false モーダルを再度表示 %>
<% if @status %>
$('[data-model_name="memo"]').filter('[data-id="<%= @memo.id %>"]').find(".todo-cards").html("<%= j(render partial: 'todos/todo', collection: @memo.todos, as: :todo) %>");

<% else %>
$("#modalArea").html("<%= j(render 'modal_form', memo: @memo, todo: @todo) %>")
$("#modalArea").find(".modal").modal('show')
<% end %>