config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {registrations: "users/registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show] do
      
  end
  
  resources :memos do
    resources :todos do
        member do
          get "sort"
        end
    end
  end
  
  resources :tweets do
      collection do
        get 'search'
        get 'favorite'
      end
      
    resources :likes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  get "users/:id" => "users#show"
  
  root to: "home#index"
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  has_many :todos, -> { order("done ASC, position ASC").includes(:memo) }, dependent: :destroy

  validates :title, presence: true
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_memo, only: [:show, :edit, :update, :destroy]

  # GET /memos
  def index
    @memos = current_user.memos.all
  end

  # GET /memos/new
  def new
    @memo = current_user.memos.new
  end

  # GET /memos/1/edit
  def edit
  end

  def show
  end
  # POST /memos
  def create
    @memo = current_user.memos.new(memo_params)

    if @memo.save
      @status = true
    else
      @status = false
    end
  end

  # PATCH/PUT /memos/1
  def update
    if @memo.update(memo_params)
      @status = true
    else
      @status = false
    end
  end

  # DELETE /memos/1
  def destroy
    @memo.destroy
  end

  private
    def set_memo
      @memo = current_user.memos.find_by(id: params[:id])
      redirect_to(memos_url, alert: "ERROR!!") if @memo.blank?
    end

    def memo_params
      params.require(:memo).permit(:title, :user_id)
    end
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/memos/_form.html.erb
<div class="modal fade" id="memoModal" tabindex="-1" role="dialog" aria-labelledby="memoModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_with(model: memo, remote: true) do |form| %>
        <div class="modal-header">
          <h4 class="modal-title text-success" id="memoModal">新規リスト</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <% if memo.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(memo.errors.count, "error") %> prohibited this memo from being saved:</h2>
              <ul>
                <% memo.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field text-success">
            <%= form.label :title, "リスト名" %>
            <%= form.text_field :title %>
          </div>
        </div>
        <div class="modal-footer actions">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
          <%= form.submit "作成" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/memos/_memo.html.erb
<div class="card bg-success d-inline-block text-wrap h-100 mx-1 memo-card"data-model_name="<%= Memo.model_name.singular %>"data-id="<%= memo.id %>">
    <div class="d-flex flex-column h-100" style="width: 25rem; min-width: 25rem;">
        <div class="font-weight-bold bg-success px-4 py-2 memo-header">
            <div class="pr-5 text-white"><%= memo.title %></div>
                <div class="text-right position-absolute" style="top: 4px; right: 4px">
                    <%# remote: true から local: trueに変更したことでdropdown-menuの操作が可能になった %>
                    <%# 改めてリスト内の新規投稿を作ろうとしたがerrorになったので remote: true へ変更した %>
                    <%# remoteオプション→form_for,form_tagに使用されるオプション localオプション→form_with %>
                    <%# Railsのver.違いで使い分けをすること %>
                    <%= link_to(new_memo_todo_path(memo), title: "New TODO", class: "btn px-0 text-white", remote: true) do %>
                        <i class="fas fa-plus align-middle"></i>
                    <% end %>
                    <div class="btn-group ">
                        <button type="button" class="btn text-white" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v align-middle"></i>
                        </button>
                        <div class="dropdown-menu dropdown-menu-right text-middle">
                            <%= link_to "編集", edit_memo_path(memo), class: "dropdown-item text-success", remote: true %>
                            <%= link_to "削除", memo, method: :delete, class: "dropdown-item text-danger", remote: true, data: { confirm: '削除しますか？' } %>
                        </div>
                    </div>
                </div>
        </div>
            <div class="card-body px-2 pb-2 pt-0 overflow-auto todo-cards">
                <%= render partial: "todos/todo", collection: memo.todos, as: :todo %>
            </div>
    </div>
</div>

app/views/memos/create.js.erb
<%# modalを閉じる処理 %>
$("#memoModal").modal("hide");
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();
<%# Rails @status => true 画面の書き換え : false モーダルを再度表示 %>
<% if @status %>
$("#memosIndex").append("<%= j(render @memo) %>");
<% else %>
$("#modalArea").html("<%= j(render 'memos/form', memo: @memo) %>")
$("#modalArea").find(".modal").modal('show')
<% end %>

app/views/memos/destroy.js.erb
<%# modalを閉じる処理 %>
$("#memoModal").modal("hide");
$("body").removeClass("modal-open");
$(".modal-backdrop").remove();

<%# 画面の書き換え %>
$('[data-model_name="memo"]').filter('[data-id="<%= @memo.id %>"]').remove();

app/views/memos/edit.js.erb
<%# モーダル追加 %>
$("#modalArea").html(
    "<%= j(render 'form', memo: @memo) %>"
);

<%# フォームにフォーカス %>
<%# modalAreaのなかから modalを探してきて、 %>
$("#modalArea").find(".modal").on('shown.bs.modal', () => {
    $("#modalArea").find("form input[type=text]")[0].focus();
})

<%# モーダル表示 %>
$("#modalArea").find(".modal").modal("show");

app/views/memos/index.html.erb
  <div class="memo-title-area px-3">
    <h4>TODOリスト</h4>
      <%= link_to new_memo_path, title: "New", class: "btn p-0 text-dark", remote: true do %>
        <div class="new">
          <i class="fas fa-plus align-middle pr-1"></i><span class="align-middle">リスト新規作成</span>
        </div>
      <% end %>
  </div>

<div class=" text-nowrap memo-index-area" id="memosIndex">
  <%= render @memos %>

  <%# Jqueryの動きを出すためのコード3種 %>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</div>

app/views/memos/new.js.erb
$("#modalArea").html("<%= j(render 'form', memo: @memo) %>")

<%# フォームにフォーカス %>
$("#modalArea").find(".modal").on('shown.bs.modal', () => {
    $("#modalArea").find("form input[type=text]")[0].focus();
})

$("#modalArea").find(".modal").modal('show')

app/views/memos/update.js.erb
<%# モーダルを閉じる処理 %>
$("#memoModal").modal("hide");
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();


<%# Rails @status => true 画面の書き換え : false モーダルを再度表示 %>
<% if @status %>
$('[data-model_name="memo"]').filter('[data-id="<%= @memo.id %>"]').replaceWith("<%= j(render @memo) %>");

<% else %>
$("#modalArea").html("<%= j(render 'form', memo: @memo) %>")
$("#modalArea").find(".modal").modal('show')
<% end %>