config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {registrations: "users/registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show] do
      
  end
  
  resources :memos do
    resources :todos do
        member do
          get "sort"
        end
    end
  end
  
  resources :tweets do
      collection do
        get 'search'
        get 'favorite'
      end
      
    resources :likes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  get "users/:id" => "users#show"
  
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

# validates_uniqueness_ofによりtweet_idとuser_idの組が1組しかないように
# バリデーションをかけました（1つしかいいねをつけられないようにする）
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  
# validates_uniqueness_ofによりtweet_idとuser_idの組が1組しかないように
# バリデーションをかけました（1つしかいいねをつけられないようにする）
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  has_many :todos, -> { order("done ASC, position ASC").includes(:memo) }, dependent: :destroy

  validates :title, presence: true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :memo
  acts_as_list scope: [:memo_id]

  validates :position, numericality: { only_integer: true, allow_nil: true }
  validates :content, presence: true
  validates :done, inclusion: { in: [true, false] }

  after_initialize :set_default, if: :new_record?

  private

  def set_default
    self.done = false if self.done.blank?
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
  # image の追加
      mount_uploader :image, ImageUploader
  # liked_usersによって投稿が誰にいいねされているのかを簡単に取得できる
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  # 上記と同様
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  # コメント機能追加
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
            :recoverable, :rememberable, :validatable
    validates :user_name, presence: true
    validates :pr, length: { maximum: 200 }
    
  # image の追加
    mount_uploader :image, ImageUploader

    has_many :tweets, dependent: :destroy

  # コメント機能
    has_many :comments

  # いいね機能
    has_many :likes, dependent: :destroy
    has_many :liked_tweets, through: :likes, source: :tweet

  # お気に入り機能
    has_many :favorites, dependent: :destroy
    has_many :favorited_tweets, through: :favorites, source: :tweet

  #Todo機能
  has_many :memos

  # 投稿に対して、すでにいいねをしているか判定する
      def already_liked?(tweet)
        self.likes.exists?(tweet_id: tweet.id)
      end
    # def like_this(clicked_tweet)
    #   self.likes.find_or_create_by(tweet: clicked_tweet)
    # end

  # 投稿に対して、すでにいいねをしているか判定する
      def already_favorited?(tweet)
        self.favorites.exists?(tweet_id: tweet.id)
      end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    # ログインしていない状態だとログイン画面に飛ばされる
    # skip_before_action :authenticate_user!, except: [:index]
    # before_action :authenticate_user!, only: [:index]

    def index
        redirect_to tweets_path if user_signed_in?
    end
    
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @like = current_user.likes.create(tweet_id: params[:tweet_id])
    redirect_back(fallback_location: root_path)
    end
    
    def destroy
        @like = current_user.likes.find_by(tweet_id: params[:tweet_id]).destroy
    redirect_back(fallback_location: root_path)
    end

    private

    def clicked_tweet
        Tweet.find(params[:tweet_id])
    end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_memo, only: [:show, :edit, :update, :destroy]

  # GET /memos
  def index
    @memos = current_user.memos.all
  end

  # GET /memos/new
  def new
    @memo = current_user.memos.new
  end

  # GET /memos/1/edit
  def edit
  end

  def show
  end
  # POST /memos
  def create
    @memo = current_user.memos.new(memo_params)

    if @memo.save
      @status = true
    else
      @status = false
    end
  end

  # PATCH/PUT /memos/1
  def update
    if @memo.update(memo_params)
      @status = true
    else
      @status = false
    end
  end

  # DELETE /memos/1
  def destroy
    @memo.destroy
  end

  private
    def set_memo
      @memo = current_user.memos.find_by(id: params[:id])
      redirect_to(memos_url, alert: "ERROR!!") if @memo.blank?
    end

    def memo_params
      params.require(:memo).permit(:title, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def bs4_bgcolor_for(flash_key)
        case flash_key
        when "success"
            "alert-success"
        when "error"
            "alert-danger"
        when "alert"
            "alert-warning"
        when "notice"
            "alert-info"
        else
            flash_key.to_s
        end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
    <div class="fixed-top mt-5 container">
    <div class="alert <%= bs4_bgcolor_for(key) %> alert-dismissable fade show my-3">
        <%= value %>
        <button class="close" data-dismiss="alert">x</button>
    </div>
    </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-expand-sm navbar-dark bg-success">
        <%# もしユーザーがログインしているならば投稿一覧画面へ %>
        <%  if user_signed_in?  %>
            <span class="navbar-brand mb-0 h1"><%= link_to 'LiNex', tweets_path, class: "navbar-brand" %></span>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            </button>
        <%# ログインしていないのならアプリ説明画面へ %>
        <% else %>
            <span class="navbar-brand mb-0 h1"><%= link_to 'LiNex', root_path, class: "navbar-brand" %></span>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            </button>
        <% end %>
        <%# <div class="d-flex pl-5"> %>
            <%# <a href="#" onclick="history.back();"><i class='fas fa-arrow-left fa-md' style='color:#ffffff'>BACK</i></a> %>
            <%# <a href="#" onclick="history.forward();"><i class='fas fa-arrow-right fa-md' style='color:#ffffff'></i></a> %>
        <%# </div> %>
        <div class="navbar-collapse justify-content-end" id="navbarNavAltMarkup">
        <%# もしユーザーがログインしているならば下記を表示 %>
        <%  if user_signed_in?  %>
            <div class="navbar-nav">
                <a class="nav-item active">
                    <%= link_to "プロフィール", user_path(current_user.id) , class: "nav-link text-light" %>
                </a>

                <a class="nav-item active">
                    <%= link_to "新規投稿", new_tweet_path, class: "nav-link text-light" %>
                </a>

                <a class="nav-item active">
                    <%= link_to "Todo", memos_path, class: "nav-link text-light" %>
                </a>
                
                <%# <td class="nav-item active"> %>
                    <%# <%= link_to "設定", user_password_path, class: "nav-link" %>
                <%# </td> %>

                <a class="nav-item text-right ml-5 pr-5">
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
                </a>
            </div>
        <%# ログインしていないのなら下記を表示 %>
        <% else %>
            <div class="navbar-nav">
                <a class="nav-item active">
                    <%= link_to "サインアップ", new_user_registration_path, class: "nav-link text-light" %>
                </a>

                <a class="nav-item active">
                    <%= link_to "ログイン", new_user_session_path, class: "nav-link text-light" %>
                </a>
        <% end %>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>LiNex</title>
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'eload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <%# ファビコン %>
      <%= favicon_link_tag('favicon.ico.jpg') %>
      <%# fontawesome %>
      <link href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" rel="stylesheet">
      <%# メディアクエリ 767pxスマホ 768pxPC、タブレット %>
      <link rel="stylesheet" href="style-sp.css" type="text/css" media="screen and (max-width:767px)">
      <link rel="stylesheet" href="style-pc.css" type="text/css" media="screen and (min-width:768px)">
    </head>
    <body>
      <%= render "layouts/header" %>
      <%= render "layouts/flash" %>
      <div id="modalArea"></div>
    <main>
        <div class="container-fruid h-100 p-2 d-flex flex-column">
          <%= yield %>
        </div>
      </main>
    
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
  </html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>LiNex</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
        <%= render "layouts/header" %>
        <%= render "layouts/flash" %>
        <main>
        <div class="container">
            <div class="row">
                <div class="col-11 col-lg-5 bg-light jumbotron mx-auto mt-4" style="box-shadow: 0 0 5px 5px rgba(0, 0, 0, 0.2)">
                <%= yield %>
                </div>
            </div>
        </div>
    </main>
    </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=devise-width, initial-scale=1.0">
        <title>LiNex</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
        <%= render "layouts/header" %>
        <%= render "layouts/flash" %>
        <main>
            <div class="container">
            <%= yield %>
            </div>
        </main>
    </body>
</html>